"""add learning_events table

Revision ID: 0fc6767cf5ba
Revises: e93378ca7e48
Create Date: 2026-09-08 20:53:55.691633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc6767cf5ba'
down_revision: Union[str, Sequence[str], None] = 'e93378ca7e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('dice', sa.Float(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_events_event'))
        batch_op.drop_index(batch_op.f('ix_learning_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_events_case_id'))

    op.drop_table('learning_events')
    # ### end Alembic commands ###
