"""add user profile fields (job_role, birth_date, school, major)

Revision ID: cdf18c142374
Revises: 6e96eba1720d
Create Date: 2026-09-13 18:12:56.103910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf18c142374'
down_revision: Union[str, Sequence[str], None] = '6e96eba1720d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_role', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('major')
        batch_op.drop_column('school')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('job_role')

    # ### end Alembic commands ###
