"""add case_slices table and volume fields

Revision ID: d5520d64e5ba
Revises: 9fa3842cf5a4
Create Date: 2026-09-08 13:59:25.000887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5520d64e5ba'
down_revision: Union[str, Sequence[str], None] = '9fa3842cf5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_slices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('slice_index', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('mask_url', sa.String(length=255), nullable=True),
    sa.Column('lesion_area_px', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'slice_index', name='uq_case_slice_index')
    )
    with op.batch_alter_table('case_slices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_slices_case_id'), ['case_id'], unique=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('representative_slice', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('representative_slice')
        batch_op.drop_column('volume_id')

    with op.batch_alter_table('case_slices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_slices_case_id'))

    op.drop_table('case_slices')
    # ### end Alembic commands ###
