"""add cases.findings_status

Revision ID: e81bbce560b5
Revises: d5520d64e5ba
Create Date: 2026-09-08 20:27:24.095322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81bbce560b5'
down_revision: Union[str, Sequence[str], None] = 'd5520d64e5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """전문가 소견(case_findings) 검토 상태 컬럼 추가.

    **추가 전용 마이그레이션이다 — 기존 데이터를 지우거나 바꾸지 않는다.**
    server_default 덕분에 이미 등록된 케이스는 전부 'needs_expert_review' 로 채워진다.
    (실제로 지금 6케이스는 소견이 비어 있으므로 이 값이 사실과 맞다.)
    """
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('findings_status', sa.String(length=30), server_default='needs_expert_review', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('findings_status')

    # ### end Alembic commands ###
