"""add admin flag and case management fields

Revision ID: e93378ca7e48
Revises: e81bbce560b5
Create Date: 2026-09-08 20:38:23.371861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93378ca7e48'
down_revision: Union[str, Sequence[str], None] = 'e81bbce560b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """운영자 권한 + 케이스 운영 필드 추가.

    **추가 전용 마이그레이션이다 — 기존 데이터를 지우거나 바꾸지 않는다.**
    server_default 로 기존 행은 안전한 쪽으로 채워진다:
      - users.is_admin  = 0 (아무도 자동으로 관리자가 되지 않는다)
      - cases.is_active = 1 (이미 서비스 중인 케이스가 갑자기 사라지지 않는다)
      - cases.difficulty = NULL (난이도는 전문가 검토 대상이라 추측해서 채우지 않는다)
    """
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
